### ISSUE TITLE
Clear fields

### ISSUE THREAD

**Issue by cerupcat** [stripe/PaymentKit#17]
Is there a method to clear fields without having the keyboard open? If I set the cardExpiryField and cardNumberField to @"", the keyboard pops up. I'd like to be able to clear the fields once a card has been submitted (so they can then submit another card).

**Comment by jflinter** [comment]
Hey @cerupcat,
This code has moved to https://github.com/stripe/stripe-ios, which now has a class called `STPPaymentCardTextField` that has similar behavior to `PTKView`. That class has a method, creatively named `clear`, that does what you're looking for, so I'd encourage you to migrate (it should take just a few minutes, and we've written a brief guide at https://github.com/stripe/paymentkit#migration). Of course, if that doesn't work for you, or you have any trouble migrating, reply here and I'll be happy to help.
Cheers!
