### ISSUE TITLE
Access to the stateMeta call

### ISSUE THREAD

**Issue by jcutrell** [stripe/PaymentKit#20]
Is it possible that this could get an update to the stateMeta call to publicize it to the delegator? It's difficult otherwise to add an inputAccessoryView if a user is utilizing the PKView inside of a larger form.

**Comment by jflinter** [comment]
Hey @jcutrell,
As part of a large refactor, this code has moved to https://github.com/stripe/stripe-ios, which now has a class called `STPPaymentCardTextField` that has similar behavior to `PTKView`. That class exposes an `inputAccessoryView` property that should address the issue you're having, so I'd encourage you to migrate (it should take just a few minutes, and we've written a brief guide at https://github.com/stripe/paymentkit#migration). Of course, if that doesn't work for you, or you have any trouble migrating, reply here and I'll be happy to help.
Cheers!

**Comment by jcutrell** [comment]
Thank you! I've moved away from this project, but I appreciate you taking the time to address the issue!

**Comment by jflinter** [comment]
No problem. Sorry it took so long : )
