### ISSUE TITLE
Textfield becomes uneditable

### ISSUE THREAD

**Issue by rsml** [stripe/PaymentKit#39]
Steps to reproduce:
* Enter 4242424242424242 as the card number
* Don't enter anything else
* Press backspace once
* Close the keyboard

Now the textfield is uneditable.

I looked into it a little, and while the textfield is uneditable, the method -firstInvalidField is returning 'self.cardExpiryField.' Since this view isn't visible, when you call 'becomeFirstResponder' on it, nothing happens.

**Comment by mhui** [comment]
+1

**Comment by jflinter** [comment]
Hey all,
As part of a large refactor, this code has moved to https://github.com/stripe/stripe-ios, which now has a class called `STPPaymentCardTextField` with similar behavior to `PTKView`. I took care to make sure `STPPaymentCardTextField` doesn't suffer from the issue you're describing, so I'd encourage you to migrate (it should take just a few minutes, and we've written a brief guide at https://github.com/stripe/paymentkit#migration). Of course, if that doesn't work for you, or you have any trouble migrating, reply here and I'll be happy to help.
Cheers!
