### ISSUE TITLE
Card input UI should optionally not become first responder by default

### ISSUE THREAD

**Issue by jflinter** [stripe/PaymentKit#48]
Migrated from https://github.com/stripe/stripe-ios/issues/27

**Comment by eligreg** [comment]
agreed!

**Comment by urte** [comment]
How can I work around this? My credit card form is at the bottom of the view, it cannot be first responder.

**Comment by knusbaum** [comment]
@urte There's a pull request #50 that will take care of it for you.

**Comment by urte** [comment]
good man. when this will be official released? I am on CocoaPod with PaymentKit 1.1.1

**Comment by knusbaum** [comment]
@urte No idea. I'm not a stripe dev, unfortunately.

**Comment by jflinter** [comment]
Yep, just merged #50, so this should be all set.

Note that I haven't cut a new Cocoapod yet, so for now I'd point your `Podfile` at the master branch of this repo:

`pod 'PaymentKit', :git => 'https://github.com/stripe/PaymentKit.git'`
