### ISSUE TITLE
Supply @3x image assets

### ISSUE THREAD

**Issue by tedlee** [stripe/PaymentKit#52]
No support yet for @3x image assets which causes UI elements to appear blurry on the iPhone 6 plus

**Comment by billburgess** [comment]
+1

**Comment by harrisnb** [comment]
+1

**Comment by schayes04** [comment]
+1

**Comment by davidrothera** [comment]
+1

**Comment by jonah-williams** [comment]
I'm surprised to see this is still an open issue. Where did the existing icons come from? Could you provide the originals and allow one of us to export 3x versions to create a pull request to resolve this?

**Comment by davidrothera** [comment]
It seems that this library doesn't really get any love anymore :( I moved away to a different CC input view a while ago :(

**Comment by jflinter** [comment]
Hey all,

First, I'm very sorry for our delay in addressing this issue. This repository has had a lot of outstanding issues for some time now, and we've recently completed a large refactor that should address most of them.

This code has moved to https://github.com/stripe/stripe-ios, which now has a class called `STPPaymentCardTextField` that has similar behavior to `PTKView`. It includes icons with @3x representations (and they've been updated as well!), so I'd encourage you to migrate (it should take just a few minutes, and we've written a brief guide at https://github.com/stripe/paymentkit#migration). Of course, if that doesn't work for you, or you have any trouble migrating, reply here and I'll be happy to help.

Cheers!

**Comment by tedlee** [comment]
Huzzah, congrats on shipping the new version! Thanks @jflinter :ok_hand:

**Comment by harrisnb** [comment]
Excellent news! 

Many thanks, Looking forward to trying it out.
