### ISSUE TITLE
Adding postal code in the PTKView

### ISSUE THREAD

**Issue by Abhishek10Dec** [stripe/PaymentKit#53]
Hello all,i am facing a huge trouble in adding postal code to the PTKView.Please advice me how to add that or share a example code with me.
Thanks all in advance.

**Comment by sorin** [comment]
+1

**Comment by mthole** [comment]
+1 — What's the recommended way of doing this?

**Comment by jflinter** [comment]
This functionality has never existed in PaymentKit - if you'd like to collect your users' billing zip code, you should simply do so with a `UITextField`.

Also, we've stopped development on this repository, and have moved most of the relevant code to https://github.com/stripe-stripe-ios. You should strongly consider migrating; there is a guide in the README.
