### ISSUE TITLE
iOS8 with Swift

### ISSUE THREAD

**Issue by JasonHough** [stripe/PaymentKit#54]
Hi there, 
I have added the new version of PaymentKit in my project which is iOS8 and swift. I have added the bridging-header. I am getting errors within the PTKView.m - Unkown type name 'NSString'

**Comment by Saravana181187** [comment]
In my coding pkview is not found how to get that..
.......
#ifndef Arcane_Bridging_Header_h
#define Arcane_Bridging_Header_h

#import <FacebookSDK/FacebookSDK.h>
#import <GoogleMaps/GoogleMaps.h>
#import "Webservice.h"
////#import "Stripe"
#import "PKView.m"   ------>//Here shows pkview.h not found
#import "STPView.m"
#endif
.......

**Comment by Saravana181187** [comment]
Then it shows Failed to import bridging header '/Users/Desktop/arcane-iphone1/Arcane/Bridging-Header.h'


What can i do for this..?

**Comment by jflinter** [comment]
Hey all,
As part of a large refactor, this code has moved to our iOS SDK at https://github.com/stripe/stripe-ios, which now has a class called `STPPaymentCardTextField` with similar behavior to `PTKView`. Our SDK has much better interoperability with Swift, so I'd encourage you to migrate (it should take just a few minutes, and we've written a brief guide at https://github.com/stripe/paymentkit#migration). Of course, if that doesn't work for you, or you have any trouble migrating, reply here and I'll be happy to help.
Cheers!
