### ISSUE TITLE
Prefix Resources

### ISSUE THREAD

**Issue by DaveBatton** [stripe/PaymentKit#55]
The resources should be prefixed with PTK just like the class names and such. Otherwise they may conflict with other resource names. This is especially likely with "placeholder.png".

For example, use PTKAmex.png rather than amex.png.

**Comment by jflinter** [comment]
Hey @DaveBatton,
As part of a large refactor, this code has moved to https://github.com/stripe/stripe-ios, which now has a class called `STPPaymentCardTextField` that has similar behavior to `PTKView`. The resources in that repository are appropriately prefixed (and the whole thing is available as a cocoa touch framework, which makes collisions impossible), so I'd encourage you to migrate (it should take just a few minutes, and we've written a brief guide at https://github.com/stripe/paymentkit#migration). Of course, if that doesn't work for you, or you have any trouble migrating, reply here and I'll be happy to help.
Cheers!
