### ISSUE TITLE
PTKView is not full width on iPhone 6 and iPhone 6 Plus when running in native resolution

### ISSUE THREAD

**Issue by madhikarma** [stripe/PaymentKit#59]
Hi, the PTKViews is positioning its subviews with fixed number sizes and setting its own frame which is used derive the other sibling / subview sizes

As a result it doesn't size its width attractive that don't work well on the iPhone 6 and iPhone 6 Plus when run at full res. @3x for 6+

Steps to reproduce 
- Add PaymentKit to project
- Ensure that project is running at @3x mode  via Lauch storyboard or Default png files in the Info plist
- Instantiate PTKView and add to view controller view and update its with when <code>viewDidLayoutSubviews</code>

Can it be fixed / refatored to support these larger device widths too or better yet refactored to use Auto Layout?

cc @danieladias

**Comment by 2ndmouse** [comment]
+1 for this. I went into this problem yesterday.

**Comment by billburgess** [comment]
The frame you set PTKView to is completely ignored (other than x and y placement). All views and subviews are hardcoded. I kinda expected more from a Stripe library. I realize it is free, but this helper view is almost unusable in the current state.

I'd love to hear from one of the Stripe devs if a rewrite and pull request would be accepted to rework the view to use auto layout, or at the very least, some better layouts given the frame passed in.

**Comment by SpringMissile** [comment]
This is ridiculous. +1

**Comment by sorin** [comment]
+1 The reason I used Stripe in the first place is that it's super easy to integrate. This is not super easy to integrate. Please make this widget flexible size and add the zip code too.

**Comment by yforjindam** [comment]
+1 Easy fix?

**Comment by N4tr0n** [comment]
+1 Please fix or at least address the comment made by @billburgess

**Comment by danieladias** [comment]
For anyone interested we ended up using this fork: https://github.com/lmcd/LMPaymentKit which is working full width in @3x (see its Readme file).

cc @madhikarma

**Comment by john-langley** [comment]
+1 ... this is brutal and shouldn't be that difficult to fix.

**Comment by jflinter** [comment]
Hey all,

First, I'm very sorry for our delay in addressing this issue. This repository has had a lot of outstanding issues for some time now, and we've recently completed a large refactor that should address most of them.

This code has moved to https://github.com/stripe/stripe-ios, which now has a class called `STPPaymentCardTextField` that has similar behavior to `PTKView`. It's designed to scale to different resolutions much more flexibly, so I'd encourage you to migrate (it should take just a few minutes, and we've written a brief guide at https://github.com/stripe/paymentkit#migration). Of course, if that doesn't work for you, or you have any trouble migrating, reply here and I'll be happy to help.

Thanks for your patience, and I hope `STPPaymentCardTextField` is a good fit for your needs.
