### ISSUE TITLE
Allows months to be entered as 00

### ISSUE THREAD

**Issue by hmlongco** [stripe/PaymentKit#62]
The as you type validation in PTKExpiry allows months to be entered as 00. 

The following change to isPartiallyValid in PTKExpiry.m corrects the problem.

    - (BOOL)isPartiallyValid
    {
        if ([self isValidLength]) {
            return [self isValidDate];
        } else {
             return ![_month isEqualToString:@"00"] && [self month] <= 12 && _year.length <= 4;
        }
    }

**Comment by jflinter** [comment]
Hey @hmlongco,
This code has moved to https://github.com/stripe/stripe-ios, which now has a class called `STPPaymentCardTextField` that has similar behavior to `PTKView`. That class shouldn't suffer from the issue you're describing, so I'd encourage you to migrate (it should take just a few minutes, and we've written a brief guide at https://github.com/stripe/paymentkit#migration). Of course, if that doesn't work for you, or you have any trouble migrating, reply here and I'll be happy to help.
Cheers!
