### ISSUE TITLE
PTKCardExpiry.m Deprecations 

### ISSUE THREAD

**Issue by jhergott** [stripe/PaymentKit#70]
NSGregorianCalendar, NSYearCalendarUnit and NSMonthCalendarUnit were all deprecated in iOS 8.0.  They're now NSCalendarIdentifierGregorian, NSCalendarUnitYear and NSCalendarUnitMonth.

**Comment by jflinter** [comment]
Hey @jhergott,
As part of a large refactor, this code has moved to https://github.com/stripe/stripe-ios, which now has a class called `STPPaymentCardTextField` that has similar behavior to `PTKView`. That class doesn't use any deprecated `NSCalendar` constants, so I'd encourage you to migrate (it should take just a few minutes, and we've written a brief guide at https://github.com/stripe/paymentkit#migration). Of course, if that doesn't work for you, or you have any trouble migrating, reply here and I'll be happy to help.
Cheers!
