### ISSUE TITLE
Fix PTKTextField.h warnings in Xcode 6.3.1

### ISSUE THREAD

**Issue by intonarumori** [stripe/PaymentKit#73]
The following warning is present in PTKTextField.h

``
/.../Pods/PaymentKit/PaymentKit/PTKTextField.h:25:54: Auto property synthesis will not synthesize property 'delegate'; it will be implemented by its superclass, use @dynamic to acknowledge intention
``

Please fix it.

**Comment by jflinter** [comment]
Hey @intonarumori,
This code has moved to https://github.com/stripe/stripe-ios, which now has a class called `STPPaymentCardTextField` that has similar behavior to `PTKView`. That class shouldn't suffer from the issue you're describing, so I'd encourage you to migrate (it should take just a few minutes, and we've written a brief guide at https://github.com/stripe/paymentkit#migration). Of course, if that doesn't work for you, or you have any trouble migrating, reply here and I'll be happy to help.
Cheers!
