### ISSUE TITLE
Missing API Delegates?

### ISSUE THREAD

**Issue by mukhortov** [stripe/PaymentKit#75]
> Included are a number of `UITextFieldDelegate` delegates: `PTKCardCVCDelegate`, `PTKCardExpiryDelegate` and `PTKCardNumberDelegate`. You can set these as the delegates of UITextField inputs, which ensures that input is limited and formatted.

I tried to use these delegates, but looks like they just doesn't exist:

![paymentkit](https://cloud.githubusercontent.com/assets/770278/7534614/d720041c-f584-11e4-85f6-ea28a4bc3721.png)

**Comment by eytanlevit** [comment]
hey, we're also looking for these delegates. any news?

**Comment by jflinter** [comment]
Hey @mukhortov and @eytanlevit,

Thanks for pointing this out - that appears to have been a documentation issue.

As part of a recent refactor, we're deprecating this repository in favor of https://github.com/stripe/stripe-ios, which now has a class called `STPPaymentCardTextField` that has similar behavior to `PTKView`. I'd encourage you to migrate (it should take just a few minutes, and we've written a brief guide at https://github.com/stripe/paymentkit#migration).

Unfortunately, `STPPaymentTextField` doesn't currently expose any of those delegate methods. Can you explain a bit more about what you're trying to do, and I'll find a way to help?

Cheers!
