### ISSUE TITLE
WARN  |  PaymentKit/PaymentKit/PTKTextField.h:25:54: warning: auto property synthesis will not synthesize property 'delegate'; it will be implemented by its superclass, use @dynamic to acknowledge intention [-Wobjc-property-synthesis]

### ISSUE THREAD

**Issue by fionaom** [stripe/PaymentKit#78]
Hi,

I am trying to update my Pod & I cannot get my podspec to validate.

Podfile
platform :ios, '6.1'
pod 'Stripe'
pod 'Stripe/ApplePay'
pod 'ApplePayStubs', :git => 'https://github.com/stripe/ApplePayStubs.git'
pod 'PaymentKit', :git => 'https://github.com/stripe/PaymentKit.git'

podspec:
Pod::Spec.new do |s|

    s.name              = 'paywith-iphone-sdk'
    s.version           = '1.0.12'
    s.summary           = 'PayWith SDK'
s.platform     = :ios, '6.1'
    s.homepage          = 'http://paywith.com'
    s.license           = {
        :type => 'BSD',
        :file => 'LICENSE'
    }
    s.author            = {
        'YOURNAME' => 'developers@paywith.com'
    }
    s.source            = {
        :git => 'https://github.com/Wantsa/paywithsdk-ios-pod-source.git',
        :tag => s.version.to_s
    }
    s.resources = 'PayWithSDK.framework/PWResources/*'
    s.public_header_files    = 'PayWithSDK.framework/Headers/*.h'
    s.source_files = 'PayWithSDK.framework/Headers/*.h'
    s.vendored_frameworks = 'PayWithSDK.framework'
    s.frameworks = 'AVFoundation'
s.dependency 'AFNetworking'
s.dependency 'Stripe'
s.dependency 'Stripe/ApplePay'
s.dependency 'ApplePayStubs'
s.dependency 'PaymentKit'
s.dependency 'CardIO'
s.requires_arc      = true
end

Pod::Spec.new do |s|

    s.name              = 'paywith-iphone-sdk'
    s.version           = '1.0.12'
    s.summary           = 'PayWith SDK'
s.platform     = :ios, '6.1'
    s.homepage          = 'http://paywith.com'
    s.license           = {
        :type => 'BSD',
        :file => 'LICENSE'
    }
    s.author            = {
        'YOURNAME' => 'developers@paywith.com'
    }
    s.source            = {
        :git => 'https://github.com/Wantsa/paywithsdk-ios-pod-source.git',
        :tag => s.version.to_s
    }
    s.resources = 'PayWithSDK.framework/PWResources/*'
    s.public_header_files    = 'PayWithSDK.framework/Headers/*.h'
    s.source_files = 'PayWithSDK.framework/Headers/*.h'
    s.vendored_frameworks = 'PayWithSDK.framework'
    s.frameworks = 'AVFoundation'
s.dependency 'AFNetworking'
s.dependency 'Stripe'
s.dependency 'Stripe/ApplePay'
s.dependency 'ApplePayStubs'
s.dependency 'PaymentKit'
s.dependency 'CardIO'
s.requires_arc      = true
end

Warning:
    - WARN  |  PaymentKit/PaymentKit/PTKTextField.h:25:54: warning: auto property synthesis will not synthesize property 'delegate'; it will be implemented by its superclass, use @dynamic to acknowledge intention [-Wobjc-property-synthesis]

**Comment by jflinter** [comment]
Hey @fionaom,
This code has moved to https://github.com/stripe/stripe-ios, which now has a class called `STPPaymentCardTextField` that has similar behavior to `PTKView`. That class shouldn't suffer from the issue you're describing, so I'd encourage you to migrate (it should take just a few minutes, and we've written a brief guide at https://github.com/stripe/paymentkit#migration). Of course, if that doesn't work for you, or you have any trouble migrating, reply here and I'll be happy to help.

Unrelated, but I'd also strongly suggest removing any references to `ApplePayStubs` from the podspec you're publishing - that library is meant for testing only, and shouldn't be included in App Store submissions.

Cheers!
