### ISSUE TITLE
Better card number state handling

### ISSUE THREAD

**Issue by jflinter** [stripe/PaymentKit#79]
The various card entry fields currently accomplish a lot of work by inserting/removing spaces; this causes a lot of issues and is accomplishable via way better means.

**Comment by zeevvax** [comment]
Any estimate on when this will be fixed?

**Comment by jflinter** [comment]
Working on it over the next few weeks - I'll update #88 with any progress; feel free to watch that issue.

**Comment by jflinter** [comment]
Closing this issue in favor of #88
