### ISSUE TITLE
Adjust look of payment view

### ISSUE THREAD

**Issue by hsavit1** [stripe/PaymentKit#84]
Is this possible? Can i adjust, for example, the cornerRadius ? Background color?

**Comment by hsavit1** [comment]
Right now, actually, the only thing i'm seeing is text. i dont see the outline at all !

**Comment by jflinter** [comment]
Hey @hsavit1,
This code has moved to https://github.com/stripe/stripe-ios, which now has a class called `STPPaymentCardTextField` that has similar behavior to `PTKView`. That class exposes `cornerRadius`, `backgroundColor`, and many other appearance-related properties, so I'd encourage you to migrate (it should take just a few minutes, and we've written a brief guide at https://github.com/stripe/paymentkit#migration). Of course, if that doesn't work for you, or you have any trouble migrating, reply here and I'll be happy to help.
Cheers!
