### ISSUE TITLE
Add support for Carthage

### ISSUE THREAD

**Issue by aleph7** [stripe/PaymentKit#85]
It should be as easy as creating a project with a shared Framework target. I could send a PR.

See https://github.com/Carthage/Carthage

**Comment by jflinter** [comment]
Hey @aleph7,
This code has moved to https://github.com/stripe/stripe-ios, which now has a class called `STPPaymentCardTextField` with similar behavior to `PTKView`. Our iOS SDK supports Carthage installation, so you should be covered there (just add `github "stripe/stripe-ios"` to your `Cartfile`). I'd encourage you to migrate (it should take just a few minutes, and we've written a brief guide at https://github.com/stripe/paymentkit#migration). Of course, if that doesn't work for you, or you have any trouble migrating, reply here and I'll be happy to help.
Cheers!
