### ISSUE TITLE
CocoaPods use_frameworks! images are not shown

### ISSUE THREAD

**Issue by sealemar** [stripe/PaymentKit#86]
Images are not loaded if used through CocoaPods with ```use_frameworks!``` modifier. The problem is well described [on StackOverflow](http://stackoverflow.com/questions/29581162/pod-paymentkit-cant-load-images-using-imagenamed)

**Comment by jflinter** [comment]
Hey @sealemar ,
This code has moved to github.com/stripe/stripe-ios, which now has a class called `STPPaymentCardTextField` that has similar behavior to `PTKView`. That class shouldn't suffer from the issue you're describing, so I'd encourage you to migrate (it should take just a few minutes, and we've written a brief guide at https://github.com/stripe/paymentkit#migration). Of course, if that doesn't work for you, or you have any trouble migrating, reply here and I'll be happy to help.
Cheers!
