### ISSUE TITLE
Invalid Card number doesn't have a red text anymore

### ISSUE THREAD

**Issue by oanaBan** [stripe/PaymentKit#90]
Hey guys,

After jmanian commit from 03 and 04 Aug, "improve isPartiallyValid " and "if it's valid then it's partially valid" invalid Card number doesn't have a red text anymore. Is there a reason for removing the red text behavior?

**Comment by jflinter** [comment]
Hey @oanaBan,
This code has moved to github.com/stripe/stripe-ios, which now has a class called `STPPaymentCardTextField` that has similar behavior to `PTKView`. That class shouldn't suffer from the issue you're describing, so I'd encourage you to migrate (it should take just a few minutes, and we've written a brief guide at https://github.com/stripe/paymentkit#migration). Of course, if that doesn't work for you, or you have any trouble migrating, reply here and I'll be happy to help.
Cheers!
